 platform :ios, '10.0'

target 'NewsApp' do
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher'
  pod 'ReachabilitySwift'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit', '~> 4.0'

  # Pods for NewsApp

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
